### ISSUE TITLE
Module not Loading

### ISSUE THREAD

**Issue by Dz3015** [mykle1/MMM-Astronauts#1]
First off, I'd like to thank you @mykle1 for all your space modules for MM.  My kid loves space and he is thrilled that he is going to have his own "space dashboard".

I'm using just about all of your modules, ISS-Live and ISS are working but none of the others.  I don't know if you are still active with any of this but I figured I'd drop an issue report.  It seems like "Astronauts" "Launches" "NASA" "NEO" are all behaving the same.  Nothing loads except the innerHTML from the 'if' statement to check if the module loaded.  It appears all the API feeds they are pulling from are still working.  I'll update if I'm able to figure anything out and resolve them.

**Comment by mykle1** [comment]
I just downloaded and tested each of the modules you mentioned. They are all working with the exception of MMM-Launch. Actually, MMM-Launch is working but it takes about 45 seconds to respond, then it performs as expected.

I'd much rather troubleshoot this on the forum, if you don't mind. Lets do one at a time. I'm sure it's something simple. What I suggest you try first is delete them from your modules folder and reclone them. Using the config entry from each module would also be a good idea. This usually solves a bunch of problems. If not, post a topic on the forum and I'll get you sorted

**Comment by Dz3015** [comment]
Sounds good, I'll open a thread on the forum and then I'll clean all the modules out tonight when I get home and load 1 to start.  It's actually happening on the Jeopardy module too so whatever it is I'm sure it's simple and will fix all of them.

Thanks!
